### ISSUE TITLE
odahuflowctl in the Docker images

### ISSUE THREAD

**Issue by mashironshiina** [odahu/odahu-flow-jupyterlab-plugin#22] opened 2020-01-20 05:58 UTC
ODAHU Platform must provide the Jupyterlab Docker images with `odahuflowctl` CLI.  Odahuflowctl has to be authenticated automatically.

**Comment by vlad-tokarev** [comment] 2020-09-25 13:34
duplicate of https://github.com/odahu/odahu-flow/issues/331

**Closed by vlad-tokarev** 2020-09-25 13:34 UTC
Labels: normal
